# Generated by Django 3.0.2 on 2020-03-09 22:46

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_testpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='tester_activities', to='web.Activities')),
            ],
        ),
    ]
