# Generated by Django 3.0.2 on 2020-03-09 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_testerpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='D5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_closed', models.BooleanField(blank=True, default=False)),
                ('price', models.PositiveIntegerField()),
                ('day1', models.ManyToManyField(related_name='d5_day1_activities', to='web.Activities')),
                ('day2', models.ManyToManyField(related_name='d5_day2_activities', to='web.Activities')),
                ('day3', models.ManyToManyField(related_name='d5_day3_activities', to='web.Activities')),
                ('day4', models.ManyToManyField(related_name='d5_day4_activities', to='web.Activities')),
                ('day5', models.ManyToManyField(related_name='d5_day5_activities', to='web.Activities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d5_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
