# Generated by Django 3.0.2 on 2020-03-09 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_auto_20200309_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='D6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('has_closed', models.BooleanField(blank=True, default=False)),
                ('price', models.PositiveIntegerField()),
                ('day1', models.ManyToManyField(related_name='d6_day1_activities', to='web.Activities')),
                ('day2', models.ManyToManyField(blank=True, related_name='d6_day2_activities', to='web.Activities')),
                ('day3', models.ManyToManyField(related_name='d6_day3_activities', to='web.Activities')),
                ('day4', models.ManyToManyField(related_name='d6_day4_activities', to='web.Activities')),
                ('day5', models.ManyToManyField(related_name='d6_day5_activities', to='web.Activities')),
                ('day6', models.ManyToManyField(related_name='d6_day6_activities', to='web.Activities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d6_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='d5',
            name='day1',
            field=models.ManyToManyField(blank=True, related_name='d5_day1_activities', to='web.Activities'),
        ),
        migrations.AlterField(
            model_name='d5',
            name='day2',
            field=models.ManyToManyField(blank=True, related_name='d5_day2_activities', to='web.Activities'),
        ),
        migrations.AlterField(
            model_name='d5',
            name='day3',
            field=models.ManyToManyField(blank=True, related_name='d5_day3_activities', to='web.Activities'),
        ),
        migrations.AlterField(
            model_name='d5',
            name='day4',
            field=models.ManyToManyField(blank=True, related_name='d5_day4_activities', to='web.Activities'),
        ),
        migrations.AlterField(
            model_name='d5',
            name='day5',
            field=models.ManyToManyField(blank=True, related_name='d5_day5_activities', to='web.Activities'),
        ),
        migrations.DeleteModel(
            name='TestPackage',
        ),
    ]
