# Generated by Django 3.0.2 on 2020-03-09 23:44

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200309_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d5',
            name='day1',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='d5_day1_activities', to='web.Activities'),
        ),
        migrations.AlterField(
            model_name='d5',
            name='day2',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='d5_day2_activities', to='web.Activities'),
        ),
        migrations.AlterField(
            model_name='d5',
            name='day3',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='d5_day3_activities', to='web.Activities'),
        ),
        migrations.AlterField(
            model_name='d5',
            name='day4',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='d5_day4_activities', to='web.Activities'),
        ),
        migrations.AlterField(
            model_name='d5',
            name='day5',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='d5_day5_activities', to='web.Activities'),
        ),
    ]
