# Generated by Django 3.0.2 on 2020-03-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200309_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='D5',
        ),
    ]
