# Generated by Django 3.0.2 on 2020-03-10 00:39

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200310_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerpackage',
            name='day2',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='tester2_activities', to='web.Activities'),
        ),
    ]
