# Generated by Django 3.0.2 on 2020-03-10 12:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0009_testerpackage_day2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_user', to=settings.AUTH_USER_MODEL)),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc9_loc', to='web.Location')),
                ('vard', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='day9_loc', to='web.Activities')),
            ],
        ),
    ]
