# Generated by Django 3.0.2 on 2020-03-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200310_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='service',
        ),
    ]
