# Generated by Django 3.0.2 on 2020-03-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_activities_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities_service', to='web.Services'),
        ),
    ]
