# Generated by Django 3.0.2 on 2020-03-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_activities_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='has_closed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
