# Generated by Django 3.0.2 on 2020-03-10 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20200310_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='loc1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc1_loc', to='web.Location'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='loc10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc10_loc', to='web.Location'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='loc2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc2_loc', to='web.Location'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='loc3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc3_loc', to='web.Location'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='loc4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc4_loc', to='web.Location'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='loc5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc5_loc', to='web.Location'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='loc6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc6_loc', to='web.Location'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='loc7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc7_loc', to='web.Location'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='loc8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc8_loc', to='web.Location'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='loc9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc9_loc', to='web.Location'),
        ),
    ]
