# Generated by Django 3.0.2 on 2020-03-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20200310_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='heading',
            field=models.CharField(default='', max_length=100),
        ),
    ]
